/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available connectors and the config each one needs. */
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{type}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a connector's config (and optionally creds) before saving. */
        post: operations["validateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch + map external data for a release into the app's schema. */
        post: operations["syncRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push locally-modified writeable fields back to the external system. */
        post: operations["pushRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The app's four canonical work-item statuses. The service must coerce to one of these.
         * @enum {string}
         */
        Status: "Not Started" | "Active" | "Blocked" | "Complete";
        MappedWorkStream: {
            externalId: string;
            fields: {
                name: string;
            };
        };
        MappedSprint: {
            externalId: string;
            fields: {
                name: string;
                /** @description YYYY-MM-DD */
                startISO: string;
                /** @description YYYY-MM-DD */
                endISO: string;
            };
        };
        MappedMember: {
            externalId: string;
            fields: {
                name: string;
                /**
                 * @description When true, this member does not count toward team capacity (e.g. EMs, PMs).
                 * Treated as a hint: applied on initial member creation; the app owns the value
                 * after that and the user may override it. Omit or false for engineers.
                 */
                nonContributing?: boolean;
            };
        };
        MappedTeam: {
            externalId: string;
            fields: {
                name: string;
            };
            members: components["schemas"]["MappedMember"][];
        };
        MappedItem: {
            externalId: string;
            /** @description External epic id; the app resolves it to a local work stream. */
            extWorkStreamId: string | null;
            /** @description External sprint id; the app resolves it to a local sprint. */
            extSprintId: string | null;
            /** @description External assignee id; the app resolves it to a local member. */
            extAssigneeId: string | null;
            fields: {
                /** @description External-provided, e.g. PROJ-123 */
                key: string;
                subject: string;
                description: string;
                status: components["schemas"]["Status"];
                points: number;
                /** @description Optional build/release label for patch items originating from a prior release (e.g. "Orion 1.5"). Set by the connector when the item's fix version differs from the current release. Null for native items. */
                build?: string | null;
                /**
                 * @description Format of the description field. Omit or text for plain text; html for HTML rich text.
                 * @enum {string}
                 */
                descriptionFormat?: "text" | "html";
                /**
                 * @description Connector-assigned work item type (e.g. Bug, Story, Task). Read-only in the app.
                 * The `id` preserves the connector's native type key for future item-creation support.
                 */
                itemType?: {
                    /** @description Connector-native type ID; null if the connector does not expose one. */
                    id: string | null;
                    /** @description Display label, e.g. Bug, Story, Task, Investigation. */
                    label: string;
                } | null;
            };
        };
        /** @description The sync payload for one release. Normalized, keyed by externalId. */
        MappedRelease: {
            /** @description Optional team + roster. When present on a connector release the app upserts members and repoints release.teamId. */
            team?: components["schemas"]["MappedTeam"] | null;
            workStreams: components["schemas"]["MappedWorkStream"][];
            sprints: components["schemas"]["MappedSprint"][];
            items: components["schemas"]["MappedItem"][];
        };
        ConnectorConfigField: {
            key: string;
            label: string;
            required: boolean;
            hint?: string;
            /**
             * @description Input type hint for the UI; controls which input control is rendered. Omit or use text for plain text inputs.
             * @enum {string}
             */
            type?: "text" | "date" | "number" | "password";
        };
        ConnectorMeta: {
            /** @description e.g. 'jira' */
            type: string;
            /** @description e.g. 'Jira' */
            label: string;
            configFields: components["schemas"]["ConnectorConfigField"][];
            /** @description Per-entity field keys the app may push back. Absent means nothing is writeable. */
            writeable?: {
                /** @description Writeable work-item fields, e.g. ['points','sprint'] */
                item?: string[];
            };
        };
        /** @description A release's binding to a backend. config holds only non-secret routing params. */
        ReleaseConnector: {
            type: string;
            config: {
                [key: string]: string;
            };
        };
        ValidateRequest: {
            config: {
                [key: string]: string;
            };
        };
        ValidateResult: {
            ok: boolean;
            error?: string;
        };
        SyncRequest: {
            connector: components["schemas"]["ReleaseConnector"];
        };
        /** @description A single writeable-field update for one work item to push back. */
        PushItemChange: {
            externalId: string;
            /** @description Only writeable fields that are locally dirty. */
            fields: {
                points?: number;
                /** @description External sprint id, or null for backlog. */
                extSprintId?: string | null;
            };
        };
        PushRequest: {
            connector: components["schemas"]["ReleaseConnector"];
            changes: components["schemas"]["PushItemChange"][];
        };
        PushResult: {
            pushed: number;
            failed: number;
            errors: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available connectors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorMeta"][];
                };
            };
        };
    };
    validateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResult"];
                };
            };
        };
    };
    syncRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description The mapped release payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappedRelease"];
                };
            };
        };
    };
    pushRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Push outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResult"];
                };
            };
        };
    };
}
